services:
  - type: web
    name: marksheet-extractor
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: path/to/your/service-account.json
